export const ADD_AUTO_PRICE = 'ADD_AUTO_PRICE';
export const ADD_AUTO_MAKE = 'ADD_AUTO_MAKE';
export const ADD_AUTO_MODEL = 'ADD_AUTO_MODEL';
export const ADD_USER_INCOME = 'ADD_USER_INCOME';
export const ADD_USER_CREDIT_SCORE = 'ADD_USER_CREDIT_SCORE';
